export const leedData = [
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "LEED for Neighborhood Development Location",
    "target": "Yes",
    "credits": 16,
    "hard": 0.00,
    "soft": 0.00,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.00,
    "budget10YrImpact": 0.00,
    "valuePremium": 0.00,
    "position": 0.00,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Net Cost Saving",
    "elevx": "✅ Commercially Justified",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "Community",
    "impactScope": "Project Wide"
  },
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Sensitive Land Protection",
    "target": "Yes",
    "credits": 1,
    "hard": 0.00,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.05,
    "budget10YrImpact": 0.05,
    "valuePremium": 0.10,
    "position": 0.00,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Low Additional CapEx",
    "elevx": "✅ Commercially Justified",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "High Priority Site and Equitable Development",
    "target": "Yes",
    "credits": 2,
    "hard": 0.25,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.35,
    "budget10YrImpact": 0.35,
    "valuePremium": 0.30,
    "position": 0.20,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Moderate CapEx – ROI Case Needed",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  }
  ,
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Surrounding Density and Diverse Uses",
    "target": "Yes",
    "credits": 5,
    "hard": 0.00,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.05,
    "budget10YrImpact": 0.05,
    "valuePremium": 0.35,
    "position": 0.20,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Low Additional CapEx",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  }
  ,
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Access to Quality Transit",
    "target": "Yes",
    "credits": 5,
    "hard": 0.15,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.25,
    "budget10YrImpact": 0.25,
    "valuePremium": 0.50,
    "position": 0.00,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Moderate CapEx – ROI Case Needed",
    "elevx": "✅ Commercially Justified",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  }
  ,
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Bicycle Facilities",
    "target": "Yes",
    "credits": 1,
    "hard": 0.15,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.20,
    "position": 0.10,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Moderate CapEx – ROI Case Needed",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  }
  ,
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Reduced Parking Footprint",
    "target": "Yes",
    "credits": 1,
    "hard": -2.50,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": -2.45,
    "budget10YrImpact": -2.45,
    "valuePremium": 0.20,
    "position": -2.55,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Net Cost Saving",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  }
  ,
  {
    "category": "LOCATION & TRANSPORTATION",
    "creditName": "Electric Vehicles",
    "target": "Yes",
    "credits": 1,
    "hard": 0.25,
    "soft": 0.10,
    "opexCosts": -0.20,
    "budgetYearImpact": 0.15,
    "budget10YrImpact": -1.12,
    "valuePremium": 0.25,
    "position": -1.25,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Moderate CapEx – ROI Case Needed",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  }
  ,
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Construction Activity Pollution Prevention",
    "target": "Yes",
    "credits": 0,
    "hard": 0.00,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.10,
    "budget10YrImpact": 0.10,
    "valuePremium": 0.00,
    "position": 0.10,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Required – Certification Only",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Site Assessment",
    "target": "",
    "credits": 1,
    "hard": 0.00,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.00,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Protect or Restore Habitat",
    "target": "",
    "credits": 2,
    "hard": 1.00,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 1.20,
    "budget10YrImpact": 1.20,
    "valuePremium": 0.50,
    "position": 0.95,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Open Space",
    "target": "",
    "credits": 1,
    "hard": 0.60,
    "soft": 0.20,
    "opexCosts": -0.20,
    "budgetYearImpact": 0.60,
    "budget10YrImpact": -0.67,
    "valuePremium": 0.80,
    "position": -1.07,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 2",
    "ownershipSensitivity": "Community-only O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Rainwater Management",
    "target": "",
    "credits": 3,
    "hard": 2.00,
    "soft": 0.30,
    "opexCosts": -0.10,
    "budgetYearImpact": 2.20,
    "budget10YrImpact": 1.56,
    "valuePremium": 1.00,
    "position": 1.06,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "❌ High Cost – Strong Strategic Rationale Needed",
    "tier": "Tier 2",
    "ownershipSensitivity": "Mixed (Community + Buildings)",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Heat Island Reduction",
    "target": "",
    "credits": 2,
    "hard": 1.00,
    "soft": 0.10,
    "opexCosts": -0.10,
    "budgetYearImpact": 1.00,
    "budget10YrImpact": 0.36,
    "valuePremium": 0.80,
    "position": -0.04,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "✅ Commercially Justified",
    "tier": "Tier 2",
    "ownershipSensitivity": "Mixed (Community + Buildings)",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "SUSTAINABLE SITES",
    "creditName": "Light Pollution Reduction",
    "target": "",
    "credits": 1,
    "hard": 0.50,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.60,
    "budget10YrImpact": 0.60,
    "valuePremium": 0.10,
    "position": 0.55,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Outdoor Water Use Reduction",
    "target": "Yes",
    "credits": 0,
    "hard": 0.50,
    "soft": 0.10,
    "opexCosts": -1.00,
    "budgetYearImpact": -0.40,
    "budget10YrImpact": -6.76,
    "valuePremium": 0.30,
    "position": -6.91,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Community + ALL",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Indoor Water Use Reduction",
    "target": "Yes",
    "credits": 0,
    "hard": 0.30,
    "soft": 0.10,
    "opexCosts": -2.00,
    "budgetYearImpact": -1.60,
    "budget10YrImpact": -14.32,
    "valuePremium": 0.20,
    "position": -14.42,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Building-Level Water Metering",
    "target": "Yes",
    "credits": 0,
    "hard": 0.10,
    "soft": 0.05,
    "opexCosts": -0.50,
    "budgetYearImpact": -0.35,
    "budget10YrImpact": -3.53,
    "valuePremium": 0.10,
    "position": -3.58,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Outdoor Water Use Reduction",
    "target": "",
    "credits": 2,
    "hard": 0.50,
    "soft": 0.10,
    "opexCosts": -1.00,
    "budgetYearImpact": -0.40,
    "budget10YrImpact": -6.76,
    "valuePremium": 0.30,
    "position": -6.91,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  }
  ,
  {
    "category": "Water Efficiency",
    "creditName": "Indoor Water Use Reduction",
    "target": "",
    "credits": 6,
    "hard": 0.30,
    "soft": 0.10,
    "opexCosts": -2.00,
    "budgetYearImpact": -1.60,
    "budget10YrImpact": -14.32,
    "valuePremium": 0.20,
    "position": -14.42,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Optimize Process Water Use",
    "target": "",
    "credits": 2,
    "hard": 0.30,
    "soft": 0.10,
    "opexCosts": -1.00,
    "budgetYearImpact": -0.60,
    "budget10YrImpact": -6.96,
    "valuePremium": 0.20,
    "position": -7.06,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 3",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Water Efficiency",
    "creditName": "Water Metering",
    "target": "",
    "credits": 1,
    "hard": 0.10,
    "soft": 0.05,
    "opexCosts": -0.50,
    "budgetYearImpact": -0.35,
    "budget10YrImpact": -3.53,
    "valuePremium": 0.10,
    "position": -3.58,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Fundamental Commissioning and Verification",
    "target": "Yes",
    "credits": 0,
    "hard": 0.00,
    "soft": 0.20,
    "opexCosts": -0.20,
    "budgetYearImpact": 0.00,
    "budget10YrImpact": -1.27,
    "valuePremium": 0.00,
    "position": -1.27,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Minimum Energy Performance",
    "target": "Yes",
    "credits": 0,
    "hard": 1.00,
    "soft": 0.30,
    "opexCosts": -5.00,
    "budgetYearImpact": -3.70,
    "budget10YrImpact": -35.50,
    "valuePremium": 2.00,
    "position": -36.50,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Building-Level Energy Metering",
    "target": "Yes",
    "credits": 0,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": -0.10,
    "budgetYearImpact": 0.10,
    "budget10YrImpact": -0.54,
    "valuePremium": 0.30,
    "position": -0.69,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Required – High Strategic Value",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Fundamental Refrigerant Management",
    "target": "Yes",
    "credits": 0,
    "hard": 0.00,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.05,
    "budget10YrImpact": 0.05,
    "valuePremium": 0.00,
    "position": 0.05,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Required – Certification Only",
    "tier": "Tier 3",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Enhanced Commissioning",
    "target": "",
    "credits": 6,
    "hard": 0.00,
    "soft": 0.30,
    "opexCosts": -0.30,
    "budgetYearImpact": 0.00,
    "budget10YrImpact": -1.91,
    "valuePremium": 0.10,
    "position": -1.96,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 2",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Optimize Energy Performance",
    "target": "",
    "credits": 18,
    "hard": 0.30,
    "soft": 0.20,
    "opexCosts": -0.50,
    "budgetYearImpact": 0.00,
    "budget10YrImpact": -3.18,
    "valuePremium": 0.30,
    "position": -3.33,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 2",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Advanced Energy Metering",
    "target": "",
    "credits": 1,
    "hard": 0.20,
    "soft": 0.10,
    "opexCosts": -0.30,
    "budgetYearImpact": 0.00,
    "budget10YrImpact": -1.91,
    "valuePremium": 0.10,
    "position": -1.96,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 3",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Grid Harmonization",
    "target": "",
    "credits": 2,
    "hard": 0.10,
    "soft": 0.05,
    "opexCosts": -0.20,
    "budgetYearImpact": -0.05,
    "budget10YrImpact": -1.32,
    "valuePremium": 0.00,
    "position": -1.32,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 3",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Renewable Energy",
    "target": "",
    "credits": 5,
    "hard": 3.00,
    "soft": 0.20,
    "opexCosts": -1.00,
    "budgetYearImpact": 2.20,
    "budget10YrImpact": -4.16,
    "valuePremium": 1.00,
    "position": -4.66,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "✅ Net Positive Investment",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "Energy and Greenhouse Gas Emissions",
    "creditName": "Enhanced Refrigerant Management",
    "target": "",
    "credits": 1,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.00,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Storage and Collection of Recyclables",
    "target": "Yes",
    "credits": 0,
    "hard": 0.05,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.15,
    "budget10YrImpact": 0.15,
    "valuePremium": 0.00,
    "position": 0.15,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Required – Certification Only",
    "tier": "Tier 3",
    "ownershipSensitivity": "Building O&M",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Building Life-Cycle Impact Reduction",
    "target": "",
    "credits": 5,
    "hard": 0.20,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.40,
    "budget10YrImpact": 0.40,
    "valuePremium": 0.20,
    "position": 0.30,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Environmental Product Declarations",
    "target": "",
    "credits": 2,
    "hard": 0.05,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.25,
    "budget10YrImpact": 0.25,
    "valuePremium": 0.10,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Community Only"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Sourcing of Raw Materials",
    "target": "",
    "credits": 2,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.10,
    "position": 0.15,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Buildings Only"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Material Ingredients",
    "target": "",
    "credits": 2,
    "hard": 0.05,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.25,
    "budget10YrImpact": 0.25,
    "valuePremium": 0.10,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "MATERIALS & RESOURCES",
    "creditName": "Construction and Demolition Waste Management",
    "target": "",
    "credits": 2,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.00,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Minimum Indoor Air Quality Performance",
    "target": "Yes",
    "credits": 0,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.00,
    "position": 0.20,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "✅ Required – Certification Only",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Environmental Tobacco Smoke Control",
    "target": "Yes",
    "credits": 0,
    "hard": 0.05,
    "soft": 0.05,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.10,
    "budget10YrImpact": 0.10,
    "valuePremium": 0.00,
    "position": 0.10,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "✅ Required – Certification Only",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Enhanced Indoor Air Quality Strategies",
    "target": "",
    "credits": 2,
    "hard": 0.20,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.30,
    "budget10YrImpact": 0.30,
    "valuePremium": 0.20,
    "position": 0.20,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Low-Emitting Materials",
    "target": "",
    "credits": 3,
    "hard": 0.05,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.15,
    "budget10YrImpact": 0.15,
    "valuePremium": 0.10,
    "position": 0.10,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Construction Indoor Air Quality Management Plan",
    "target": "",
    "credits": 1,
    "hard": 0.00,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.10,
    "budget10YrImpact": 0.10,
    "valuePremium": 0.00,
    "position": 0.10,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Strong Commercial Case",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Indoor Air Quality Assessment",
    "target": "",
    "credits": 2,
    "hard": 0.10,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.20,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.05,
    "position": 0.18,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "✅ Viable with Clear Benefits",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 3",
    "ownershipSensitivity": "Community + ALL",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Thermal Comfort",
    "target": "",
    "credits": 1,
    "hard": 0.50,
    "soft": 0.10,
    "opexCosts": -0.10,
    "budgetYearImpact": 0.50,
    "budget10YrImpact": -0.14,
    "valuePremium": 0.50,
    "position": -0.39,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Positive Outcome – Commercially Favourable",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Interior Lighting",
    "target": "",
    "credits": 2,
    "hard": 0.40,
    "soft": 0.20,
    "opexCosts": -0.10,
    "budgetYearImpact": 0.50,
    "budget10YrImpact": -0.14,
    "valuePremium": 0.30,
    "position": -0.29,
    "leedOrBau": "LEED-Induced",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "✅ Positive Outcome – Commercially Favourable",
    "tier": "Tier 2",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Daylight",
    "target": "",
    "credits": 3,
    "hard": 1.50,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 1.70,
    "budget10YrImpact": 1.70,
    "valuePremium": 0.70,
    "position": 1.35,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "❌ High Cost – Needs Strong Strategic Rationale",
    "elevx": "❌ High Cost – Strong Strategic Rationale Needed",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Quality Views",
    "target": "",
    "credits": 1,
    "hard": 0.50,
    "soft": 0.20,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.70,
    "budget10YrImpact": 0.70,
    "valuePremium": 0.70,
    "position": 0.35,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  },
  {
    "category": "INDOOR ENVIRONMENT QUALITY",
    "creditName": "Acoustic Performance",
    "target": "",
    "credits": 1,
    "hard": 0.30,
    "soft": 0.10,
    "opexCosts": 0.00,
    "budgetYearImpact": 0.40,
    "budget10YrImpact": 0.20,
    "valuePremium": 0.00,
    "position": 0.20,
    "leedOrBau": "Baseline Best Practice",
    "commercialLabel": "⚠️ Higher Cost, Requires ROI Justification",
    "elevx": "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    "tier": "Tier 1",
    "ownershipSensitivity": "N/A",
    "costSource": "REFINED",
    "assetClass": "",
    "impactScope": "Project Wide"
  }
];