export const leedData = [
  {
    category: "Integrated Process",
    creditName: "Integrative project planning and design",
    target: "Yes",
    credits: 0,
    hard: -0.20,
    soft: 0.05,
    opexCosts: 0.00,
    budgetYearImpact: -0.15,
    budget10YrImpact: -0.15,
    valuePremium: 0.00,
    position: -0.30,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Net Cost Saving",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Integrated Process",
    creditName: "Green Building Policy and Incentives",
    target: "Yes",
    credits: 5,
    hard: 0.00,
    soft: 0.05,
    opexCosts: -0.10,
    budgetYearImpact: -0.05,
    budget10YrImpact: -0.69,
    valuePremium: 0.00,
    position: -0.69,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Low Additional CapEx",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Building O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
    
  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Ecosystems Assessment",
    target: "Yes",
    credits: 0,
    hard: 0.00,
    soft: 0.10,
    opexCosts: 0.00,
    budgetYearImpact: 0.10,
    budget10YrImpact: 0.10,
    valuePremium: 0.00,
    position: 0.10,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Moderate CapEx – ROI Case Needed",
    elevx: "✅ Required – Certification Only",
    tier: "Tier 3",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Construction Activity Pollution Prevention",
    target: "Yes",
    credits: 0,
    hard: 0.00,
    soft: 0.05,
    opexCosts: 0.00,
    budgetYearImpact: 0.05,
    budget10YrImpact: 0.05,
    valuePremium: 0.00,
    position: 0.05,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Low Additional CapEx",
    elevx: "✅ Required – Certification Only",
    tier: "Tier 3",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Green Spaces",
    target: "Yes",
    credits: 0,
    hard: 0.60,
    soft: 0.10,
    opexCosts: 0.10,
    budgetYearImpact: 0.80,
    budget10YrImpact: 1.44,
    valuePremium: 1.15,
    position: 0.86,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Elevated CapEx – Strategic Review Required",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"

  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Natural Resources Conservation and Restoration",
    target: "Yes",
    credits: 2,
    hard: 0.05,
    soft: 0.05,
    opexCosts: 0.00,
    budgetYearImpact: 0.10,
    budget10YrImpact: 0.10,
    valuePremium: 0.20,
    position: 0.00,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Moderate CapEx – ROI Case Needed",
    elevx: "✅ Commercially Justified",
    tier: "Tier 3",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Light Pollution Reduction",
    target: "Yes",
    credits: 2,
    hard: 0.05,
    soft: 0.05,
    opexCosts: -0.05,
    budgetYearImpact: 0.05,
    budget10YrImpact: -0.27,
    valuePremium: 0.20,
    position: -0.37,
    leedOrBau: "LEED-Induced",
    commercialLabel: "⚠️ Moderate CapEx – ROI Case Needed",
    elevx: "✅ Positive Outcome – Commercially Favourable",
    tier: "Tier 3",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Natural Systems and Ecology",
    creditName: "Resilience Planning",
    target: "Yes",
    credits: 6,
    hard: 0.20,
    soft: 0.10,
    opexCosts: -0.10,
    budgetYearImpact: 0.20,
    budget10YrImpact: -0.44,
    valuePremium: 0.20,
    position: -0.54,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Moderate CapEx – ROI Case Needed",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Transport",
    creditName: "Compact / Mixed Use",
    target: "Yes",
    credits: 4,
    hard: 1.00,
    soft: 0.10,
    opexCosts: -0.10,
    budgetYearImpact: 1.00,
    budget10YrImpact: 0.36,
    valuePremium: 0.55,
    position: 0.09,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "❌ High Cost – Needs Strong Strategic Rationale",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Transport",
    creditName: "Walkability and Bikeability",
    target: "Yes",
    credits: 2,
    hard: 0.30,
    soft: 0.05,
    opexCosts: -0.05,
    budgetYearImpact: 0.30,
    budget10YrImpact: -0.02,
    valuePremium: 1.15,
    position: -0.59,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Transport",
    creditName: "Access to Quality Transit",
    target: "Yes",
    credits: 2,
    hard: 1.00,
    soft: 0.05,
    opexCosts: -0.05,
    budgetYearImpact: 1.00,
    budget10YrImpact: 0.68,
    valuePremium: 1.15,
    position: 0.11,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "❌ High Cost – Needs Strong Strategic Rationale",
    elevx: "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Transport",
    creditName: "Alternative Fuel Vehicles",
    target: "Yes",
    credits: 2,
    hard: 0.40,
    soft: 0.05,
    opexCosts: 0.10,
    budgetYearImpact: 0.55,
    budget10YrImpact: 1.19,
    valuePremium: 0.55,
    position: 0.91,
    leedOrBau: "LEED-Induced",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Transport",
    creditName: "Smart Mobility and Transportation Policy",
    target: "Yes",
    credits: 2,
    hard: 0.40,
    soft: 0.10,
    opexCosts: -0.20,
    budgetYearImpact: 0.30,
    budget10YrImpact: -0.97,
    valuePremium: 0.55,
    position: -1.25,
    leedOrBau: "LEED-Induced",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Transport",
    creditName: "High Priority Sites",
    target: "No",
    credits: 0,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.00,
    position: 0.00,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Water Efficiency",
    creditName: "Integrated Water Management",
    target: "Yes",
    credits: 0,
    hard: 0.10,
    soft: 0.10,
    opexCosts: -0.05,
    budgetYearImpact: 0.15,
    budget10YrImpact: -0.17,
    valuePremium: 0.20,
    position: -0.27,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Water Efficiency",
    creditName: "Water Access and Quality",
    target: "Yes",
    credits: 0,
    hard: 0.10,
    soft: 0.10,
    opexCosts: -0.10,
    budgetYearImpact: 0.10,
    budget10YrImpact: -0.54,
    valuePremium: 0.20,
    position: -0.64,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Water Efficiency",
    creditName: "Stormwater Management",
    target: "Yes",
    credits: 4,
    hard: 0.50,
    soft: 0.15,
    opexCosts: -0.20,
    budgetYearImpact: 0.45,
    budget10YrImpact: -0.82,
    valuePremium: 0.20,
    position: -0.92,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Water Efficiency",
    creditName: "Wastewater Management",
    target: "Yes",
    credits: 3,
    hard: 0.50,
    soft: 0.15,
    opexCosts: -0.20,
    budgetYearImpact: 0.45,
    budget10YrImpact: -0.82,
    valuePremium: 0.20,
    position: -0.92,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Water Efficiency",
    creditName: "Smart Water Systems",
    target: "Yes",
    credits: 2,
    hard: 0.10,
    soft: 0.10,
    opexCosts: -0.05,
    budgetYearImpact: 0.15,
    budget10YrImpact: -0.17,
    valuePremium: 1.15,
    position: -0.74,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Energy and Greenhouse Gas Emissions",
    creditName: "Energy and Greenhouse gas Emissions Management",
    target: "Yes",
    credits: 13,
    hard: -0.05,
    soft: 0.15,
    opexCosts: -0.15,
    budgetYearImpact: -0.05,
    budget10YrImpact: -1.00,
    valuePremium: 0.20,
    position: -1.10,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Net Positive Investment",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Energy and Greenhouse Gas Emissions",
    creditName: "Power Access, Reliability and Resiliency",
    target: "Yes",
    credits: 0,
    hard: 0.20,
    soft: 0.10,
    opexCosts: -0.20,
    budgetYearImpact: 0.10,
    budget10YrImpact: -1.17,
    valuePremium: 0.55,
    position: -1.45,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Energy and Greenhouse Gas Emissions",
    creditName: "Energy Efficiency",
    target: "Yes",
    credits: 2,
    hard: 0.20,
    soft: 0.10,
    opexCosts: -0.60,
    budgetYearImpact: -0.30,
    budget10YrImpact: -4.12,
    valuePremium: 1.15,
    position: -4.69,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Energy and Greenhouse Gas Emissions",
    creditName: "Renewable Energy",
    target: "No",
    credits: 0,
    hard: 1.00,
    soft: 0.50,
    opexCosts: -1.00,
    budgetYearImpact: 0.50,
    budget10YrImpact: -5.86,
    valuePremium: 0.00,
    position: -5.86,
    leedOrBau: "LEED-Induced",
    commercialLabel: "❌ High Cost – Needs Strong Strategic Rationale",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Energy and Greenhouse Gas Emissions",
    creditName: "Grid Harmonisation",
    target: "Yes",
    credits: 1,
    hard: 0.10,
    soft: 0.10,
    opexCosts: 0.00,
    budgetYearImpact: 0.20,
    budget10YrImpact: 0.20,
    valuePremium: 0.20,
    position: 0.10,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Materials and Resources",
    creditName: "Construction and Demolition Waste Management",
    target: "Yes",
    credits: 0,
    hard: 0.02,
    soft: 0.01,
    opexCosts: 0.00,
    budgetYearImpact: 0.03,
    budget10YrImpact: 0.03,
    valuePremium: 0.00,
    position: 0.03,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Required – Certification Only",
    tier: "Tier 3",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide"
  },
  {
    category: "Materials and Resources",
    creditName: "Solid Waste Management",
    target: "Yes",
    credits: 0,
    hard: 0.20,
    soft: 0.05,
    opexCosts: -0.15,
    budgetYearImpact: 0.10,
    budget10YrImpact: -0.85,
    valuePremium: 0.20,
    position: -0.95,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Materials and Resources",
    creditName: "Organic Waste Treatment",
    target: "No",
    credits: 0,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.00,
    position: 0.00,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Materials and Resources",
    creditName: "Recycling Infrastructure",
    target: "Yes",
    credits: 2,
    hard: 0.10,
    soft: 0.05,
    opexCosts: -0.05,
    budgetYearImpact: 0.10,
    budget10YrImpact: -0.22,
    valuePremium: 0.10,
    position: -0.27,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Positive Outcome – Commercially Favourable",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Materials and Resources",
    creditName: "Responsible Sourcing",
    target: "Yes",
    credits: 1,
    hard: 0.10,
    soft: -0.05,
    opexCosts: 0.00,
    budgetYearImpact: 0.05,
    budget10YrImpact: 0.05,
    valuePremium: 0.20,
    position: -0.05,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Materials and Resources",
    creditName: "Smart Waste Management Systems",
    target: "Yes",
    credits: 2,
    hard: 0.10,
    soft: 0.05,
    opexCosts: -0.20,
    budgetYearImpact: -0.05,
    budget10YrImpact: -1.32,
    valuePremium: 0.55,
    position: -1.60,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Quality of Life",
    creditName: "Demographic Assessment",
    target: "Yes",
    credits: 0,
    hard: 0.00,
    soft: 0.10,
    opexCosts: 0.00,
    budgetYearImpact: 0.10,
    budget10YrImpact: 0.10,
    valuePremium: 0.00,
    position: 0.10,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Required – Certification Only",
    tier: "Tier 3",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only"
  },
  {
    category: "Quality of Life",
    creditName: "Social Infrastructure",
    target: "Yes",
    credits: 0,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.00,
    position: 0.00,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Required – High Strategic Value",
    tier: "Tier 1",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Quality of Life",
    creditName: "Affordable Housing",
    target: "No",
    credits: 0,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.00,
    position: 0.00,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Quality of Life",
    creditName: "Public Health",
    target: "Yes",
    credits: 2,
    hard: 0.10,
    soft: 0.10,
    opexCosts: -0.01,
    budgetYearImpact: 0.19,
    budget10YrImpact: 0.13,
    valuePremium: 0.55,
    position: -0.15,
    leedOrBau: "Baseline Best Practice",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "✅ Positive Outcome – Commercially Favourable",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only",
  },
  {
    category: "Quality of Life",
    creditName: "Emergency Management and Response",
    target: "Yes",
    credits: 2,
    hard: 0.05,
    soft: 0.10,
    opexCosts: -0.01,
    budgetYearImpact: 0.14,
    budget10YrImpact: 0.08,
    valuePremium: 0.20,
    position: -0.02,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Community Only",
  },
  {
    category: "Innovation",
    creditName: "Innovation 1: Passive Design",
    target: "No",
    credits: 0,
    hard: -0.10,
    soft: 0.10,
    opexCosts: -0.10,
    budgetYearImpact: -0.10,
    budget10YrImpact: -0.74,
    valuePremium: 0.55,
    position: -1.01,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Net Positive Investment",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Building O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Buildings Only"
  },
  {
    category: "Innovation",
    creditName: "Innovation 2: Digital Twin",
    target: "Yes",
    credits: 1,
    hard: 0.30,
    soft: 0.15,
    opexCosts: -0.30,
    budgetYearImpact: 0.15,
    budget10YrImpact: -1.76,
    valuePremium: 0.20,
    position: -1.86,
    leedOrBau: "LEED-Induced",
    commercialLabel: "⚠️ Higher Cost, Requires ROI Justification",
    elevx: "✅ Net Positive Investment",
    tier: "Tier 1",
    ownershipSensitivity: "Community-only O&M",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Innovation",
    creditName: "Innovation 3: LEED AP",
    target: "Yes",
    credits: 1,
    hard: 0.00,
    soft: 0.01,
    opexCosts: 0.00,
    budgetYearImpact: 0.01,
    budget10YrImpact: 0.01,
    valuePremium: 0.00,
    position: 0.01,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "N/A",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Project Wide",
  },
  {
    category: "Innovation",
    creditName: "Innovation 4: Carbon offset",
    target: "No",
    credits: 0,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.00,
    position: 0.00,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Commercially Justified",
    tier: "Tier 2",
    ownershipSensitivity: "N/A",
    costSource: "REFINED",
    assetClass: "Community",
    impactScope: "Project Wide",
  },
  {
    category: "Innovation",
    creditName: "Exemplary 1: Construction and Demolition Waste Management",
    target: "Yes",
    credits: 1,
    hard: 0.10,
    soft: 0.02,
    opexCosts: 0.00,
    budgetYearImpact: 0.12,
    budget10YrImpact: 0.12,
    valuePremium: 0.00,
    position: 0.12,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Viable with Clear Benefits",
    elevx: "⚠️ Minor Net Gain – Proceed if Strategically Aligned",
    tier: "Tier 2",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Regional Priority",
    creditName: "Rain Water Management for attempting storm water management (3 points) (ND)",
    target: "Yes",
    credits: 1,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.55,
    position: -0.28,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Positive Outcome – Commercially Favourable",
    tier: "Tier 2",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  },
  {
    category: "Regional Priority",
    creditName: "Energy and Greenhouse gas Emissions Management for attempting 9 points (BD+C)",
    target: "Yes",
    credits: 1,
    hard: 0.00,
    soft: 0.00,
    opexCosts: 0.00,
    budgetYearImpact: 0.00,
    budget10YrImpact: 0.00,
    valuePremium: 0.55,
    position: -0.28,
    leedOrBau: "LEED-Induced",
    commercialLabel: "✅ Strong Commercial Case",
    elevx: "✅ Positive Outcome – Commercially Favourable",
    tier: "Tier 2",
    ownershipSensitivity: "Mixed (Community + Buildings)",
    costSource: "REFINED",
    assetClass: "Community + ALL",
    impactScope: "Project Wide",
  }
];